### ISSUE TITLE
DEV-16 Refactor Google Map API calls and redirect the retrieval of info 

### ISSUE THREAD

**Issue by nguyhh** [MaelSemler/mini-cap#111]
Since choosing transportation method and getting route alternatives all come from the Google map API. Need to refactor the request call and the organization of all the informations retrieved.

**Comment by MaelSemler** [comment]
There is already an issue called DEV-16, I will change the name

**Comment by nguyhh** [comment]
- [x] DirectionService: To make the request
- [x] Directions Class: To make store the alternative routes 
- [x] Path Class: Hold the parameters from the user inputs like transportation, destination, origin. It also holds the information displayed on the screen such as: Total travel time, total distance and directions steps instructions returned.
