### ISSUE TITLE
FT1-5 See distinguishable Concordia buildings on the map.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#19]
A user wants to easily see which buildings are Concordia buildings on the map so that they don't have to search for them for a long time.

**Comment by lposo** [comment]
- [ ] See Loyola Campus buildings highlighted on the map.
- [ ] See JMSB Campus buildings highlighted on the map.

**Comment by nguyhh** [comment]
- [ ] Identifies SGW campus Buildings
- [ ] Identifies Loyola campus Buildings
- [ ] See them in dark-colored buildings

**Comment by nguyhh** [comment]
I feel like we are gonna be rewriting the same code if we split it by campus, because the code would be doing the exact same thing identify them then color them?

**Comment by MaelSemler** [comment]
Mockup: https://drive.google.com/file/d/1Y_MJw4FMMR95nPqtGIPTFoozxmkoSl5a/view?usp=sharing

**Comment by lposo** [comment]
I was looking at this part of the maps API, for polygons:
https://developers.google.com/maps/documentation/android-sdk/shapes
I figured we'd be defining the shapes of each building in a campus.
