### ISSUE TITLE
FT2-1 Pick my starting location.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#22]
Users can manually select where they want to begin their route.

**Comment by Khal-Shah** [comment]
> Given that I am on the map page,
> I can click on the upper text box,
> Then I can type in to set my starting location.
>

**Comment by daphneaugier** [comment]
Mockup : 
<img width="273" alt="Capture d’écran 2020-03-05 à 19 28 50" src="https://user-images.githubusercontent.com/35980232/76038535-cf98b700-5f17-11ea-954c-46898da23e94.png">
