### ISSUE TITLE
FT2-3  Pick my destination building.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#24]
Users can manually select where they want to go on campus.

**Comment by Khal-Shah** [comment]
> Given that I am on the map page,
> I can click on the lower text box, 
> then, I can type in my destination building's name or address
>

**Comment by MaelSemler** [comment]
Mockup: https://drive.google.com/file/d/1XgPQQU4hw2uAZneQg0A5tthybhs6nqom/view?usp=sharing
