### ISSUE TITLE
FT2-4 Get directions from my starting location to my destination.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#25]
**Description**
Users will be given directions on how to get from their starting location to their destination.

**Comment by MaelSemler** [comment]
Given that I am on the map page,
I can select my starting location,
And I can select my destination,
and I can click “start”,
Then I should see directions to reach my destination.

**Comment by nguyhh** [comment]
- [ ] Select Starting Location 
- [ ] Select Destination
- [X] Click Start/Route
- [X] Map clearly identify the path
- [X] Directions shown
