### ISSUE TITLE
FT2-9 Pick from a selection of different routes. 

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#30]
Users can select from different alternate routes that are not the shortest route.

**Comment by MaelSemler** [comment]
Given that I am on the map page,
And I have put in my current location, and destination
I can click start and choose a transportation method,
I can click to choose from the suggested routes

**Comment by daphneaugier** [comment]
Acceptance criteria :
- [ ]  As the user types, suggestions show up in the results
- [ ]  Informations related to the selected building shows up
- [ ]  Navigation page loads with current location as the default starting location
- [ ]  Navigation page reloads with route suggestions with the selected transportation mode
- [ ]  Navigation page reloads with the selected route 
- [ ]  Navigation page reloads all route suggestions results
