### ISSUE TITLE
FT3-7 Want the directions to my next class from my current location. 

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#38]
Users can see the fastest route from their current location to the building of their next class.

**Comment by MaelSemler** [comment]
Given that I have successfully logged in,
From the hamburger menu,
I can click on “Next Event”,
And I can click on “Go now”, 
Then, I should be able to see directions to my next class.

**Comment by nguyhh** [comment]
Once your event is retrieved from the calendar you only need to call: 
`route(currentLocation, Destination)`
