### ISSUE TITLE
FT4-2 Locate rooms for a specific floor.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#40]
**Description**
Users can see the location of a room in the floor plan of a given floor.  Given that I am on the map page, I can click on the search bar and I can type in a specific room, then I should be able to see the room in the map indicating the building and the floor level.

**Comment by MaelSemler** [comment]
Given that I am on the map page, 
I can click on the search bar,
And I can type in a specific room,
Then I should be able to see the room in the map indicating the building and the floor level.

**Comment by daphneaugier** [comment]
**UI Mockup** 
Portrait: 
<img width="271" alt="Capture d’écran 2020-03-05 à 19 48 22" src="https://user-images.githubusercontent.com/35980232/76039388-48990e00-5f1a-11ea-88f4-aeb266bb2b36.png">

Landscape:
<img width="730" alt="Capture d’écran 2020-03-05 à 19 47 58" src="https://user-images.githubusercontent.com/35980232/76039395-4c2c9500-5f1a-11ea-96da-bfadddf6f40c.png">
