### ISSUE TITLE
FT4-3 Choose my destination room.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#41]
The user can select a room of a concordia building to be their destination.

**Comment by MaelSemler** [comment]
Given that I am on the map page,
I can select my starting location,
And I can click on the destination text field,
And I can search for a specific room.

**Comment by daphneaugier** [comment]
**UI Mockup**
Portrait:
<img width="271" alt="Capture d’écran 2020-03-05 à 19 48 22" src="https://user-images.githubusercontent.com/35980232/76039660-189e3a80-5f1b-11ea-93ee-a9278f96daac.png">

Landscape:
<img width="730" alt="Capture d’écran 2020-03-05 à 19 47 58" src="https://user-images.githubusercontent.com/35980232/76039676-1e941b80-5f1b-11ea-98d9-ca404e37ec00.png">
