### ISSUE TITLE
FT4-4 Shortest path from my starting room to my destination room.

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#42]
The app will give the shortest path for the route selected, for the indoor path in a building.

**Comment by MaelSemler** [comment]
Given that I am on the map page,
And I have put in my current location room, and destination room,
I can click start,
Then it will show me all suggested routes but the default one will be the shortest path.

**Comment by daphneaugier** [comment]
**UI Mockup**
Portrait:
<img width="274" alt="Capture d’écran 2020-03-05 à 19 55 39" src="https://user-images.githubusercontent.com/35980232/76039751-58fdb880-5f1b-11ea-8900-9bfbd5afa3e7.png">
