### ISSUE TITLE
DEV-3 Search field at the bottom

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#74]

**Comment by MaelSemler** [comment]
Field at the bottom, recenter to the location as well

**Comment by daphneaugier** [comment]
Mockup for empty bottom search field : 
<img width="272" alt="Capture d’écran 2020-03-05 à 15 37 19" src="https://user-images.githubusercontent.com/35980232/76026727-5be9b080-5efd-11ea-9f32-f0e89c7a140a.png">

Mockup for non-empty bottom search field : 
<img width="272" alt="Capture d’écran 2020-03-05 à 15 37 33" src="https://user-images.githubusercontent.com/35980232/76026755-67d57280-5efd-11ea-82fa-4b2d4ad9f250.png">

**Comment by daphneaugier** [comment]
- Empty-search bar:
- [ ] Create fragment
- [ ] Create search bar with magnifying loop

- Full-search bar:
- [ ] Create fragment
- [ ] Create search bar with cross and go-arrow
- [ ] Fill in the search field
