### ISSUE TITLE
DEV-8 Hide the top fields

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#79]
**Description**
Top fields should only appear when clicked from the bottom search bar 

Acceptance Criteria

- [ ] Top Field no longer appears unprompted

- [ ] Top Field only appears when user clicks on bottom search bar

**Comment by Khal-Shah** [comment]
- **Modify back button**
From P.O. meeting: make back button slightly smaller. 

---

- **Fix DEF-8**
Shadow is displayed between the “Origin” and “Destination” input fields
![image.png](https://images.zenhubusercontent.com/5e1f8fd2a8ad74332ad0197f/93266ef8-0fcb-4e36-9250-16a3b8125e13)

---

- **Keep top field hidden**
Should appear once the go to arrow in the bottom search field is pressed.

**UI**
![image.png](https://images.zenhubusercontent.com/5e1f8fd2a8ad74332ad0197f/c9e2cfd1-f4fb-4e29-bde9-57fba61ff8a3)

After pressing the rotated arrow next to the displayed location in the bottom search field, the top field should look like the following:

![image.png](https://images.zenhubusercontent.com/5e1f8fd2a8ad74332ad0197f/b5309f02-e3eb-4301-89b1-bdc1996867b1)
