### ISSUE TITLE
DEV-9 Autocomplete on search fields

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#80]
**Description**
When a user clicks on a search field, there should be real-time suggestions as they type their desired location

**Comment by daphneaugier** [comment]
**UI Mockup**
Portrait: 
<img width="271" alt="Capture d’écran 2020-03-05 à 20 13 56" src="https://user-images.githubusercontent.com/35980232/76040640-eb06c080-5f1d-11ea-8bae-e5bae68d1742.png">

Landscape:
<img width="731" alt="Capture d’écran 2020-03-05 à 20 14 45" src="https://user-images.githubusercontent.com/35980232/76040677-feb22700-5f1d-11ea-9b12-d56b177f27a1.png">

**Comment by yabdelkawy** [comment]
Acceptance Criteria 

- [ ] The feature must complete a user's entry 

- [ ] The feature must suggest all nearby places according to the user's entry

- [ ] The feature must display an empty "Heart" icon (non-functional)

**Comment by yabdelkawy** [comment]
https://github.com/MaelSemler/mini-cap/issues/80
