### ISSUE TITLE
DEV-12 Import Shuttle bus schedule

### ISSUE THREAD

**Issue by MaelSemler** [MaelSemler/mini-cap#83]
**Description**
Import Concordia University's Shuttle Bus Schedule into project

**Comment by daphneaugier** [comment]
Schedule to be inputted : 
<img width="520" alt="Capture d’écran 2020-04-01 à 16 53 37" src="https://user-images.githubusercontent.com/35980232/78186748-43f14800-743b-11ea-87a0-bd3ecb52d0c2.png">

**Comment by daphneaugier** [comment]
I am having a really hard time to add the shuttle bus line. It seems particularly long to create the JSON file to add all the coordinates of the shuttle bus path.

**Comment by daphneaugier** [comment]
@yabdelkawy had in mind to :

> add a new clickable alt route that reflects the shuttle bus but we wouldn't need to integrate it with Google Maps.`

Which is a really great idea as we only have one bus stop (the destination). Will work with her on this later this week!

**Comment by daphneaugier** [comment]
Having issues to make the shuttle bus time-aware. Troubles regarding the reading of the .xml file where the schedule is inputted.
