### ISSUE TITLE
DEF-9-Application

### ISSUE THREAD

**Issue by nguyhh** [MaelSemler/mini-cap#99]
**Describe the bug**
Since the refactoring of the application, it is not possible to use the built-in emulator to test/run the application. It would simply crash. If you plug in your phone it is working fine. 

**To Reproduce**
1. Go to Android Studio
2. Click on 'run' app
3. Emulator will open
4. A crash message will appear/or  stay blank

**Expected behavior**
It is expected to open up the application

**Screenshots**
![Screenshot from 2020-03-15 00-40-01](https://user-images.githubusercontent.com/32082113/76695525-ff059d00-6656-11ea-84e4-2eaf21b98310.png)

**Desktop (please complete the following information):**
 - OS: Linux Elementary OS

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL API 23

**Additional info**
It might be because of the navigation component that we added. It is known that only recent version of Android support it. We will need to investigate that.

**Comment by yabdelkawy** [comment]
Bug was fixed and now emulator runs properly.
